/// قاعدة بيانات كاملة لسور القرآن الكريم

/// قاعدة بيانات كاملة لسور القرآن الكريم
/// تحتوي على جميع السور الـ114 مع معلوماتها الكاملة

class SurahInfo {
  final int number;
  final String nameArabic;
  final String nameEnglish;
  final int totalAyahs;
  final int juz;
  final String revelationType;

  const SurahInfo({
    required this.number,
    required this.nameArabic,
    required this.nameEnglish,
    required this.totalAyahs,
    required this.juz,
    required this.revelationType,
  });
}

class QuranDataFull {
  static const List<SurahInfo> allSurahs = [
    SurahInfo(
        number: 1,
        nameArabic: 'الفاتحة',
        nameEnglish: 'Al-Fatihah',
        totalAyahs: 7,
        juz: 1,
        revelationType: 'مكية'),
    SurahInfo(
        number: 2,
        nameArabic: 'البقرة',
        nameEnglish: 'Al-Baqarah',
        totalAyahs: 286,
        juz: 1,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 3,
        nameArabic: 'آل عمران',
        nameEnglish: 'Ali \'Imran',
        totalAyahs: 200,
        juz: 3,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 4,
        nameArabic: 'النساء',
        nameEnglish: 'An-Nisa',
        totalAyahs: 176,
        juz: 4,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 5,
        nameArabic: 'المائدة',
        nameEnglish: 'Al-Ma\'idah',
        totalAyahs: 120,
        juz: 6,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 6,
        nameArabic: 'الأنعام',
        nameEnglish: 'Al-An\'am',
        totalAyahs: 165,
        juz: 7,
        revelationType: 'مكية'),
    SurahInfo(
        number: 7,
        nameArabic: 'الأعراف',
        nameEnglish: 'Al-A\'raf',
        totalAyahs: 206,
        juz: 8,
        revelationType: 'مكية'),
    SurahInfo(
        number: 8,
        nameArabic: 'الأنفال',
        nameEnglish: 'Al-Anfal',
        totalAyahs: 75,
        juz: 9,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 9,
        nameArabic: 'التوبة',
        nameEnglish: 'At-Tawbah',
        totalAyahs: 129,
        juz: 10,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 10,
        nameArabic: 'يونس',
        nameEnglish: 'Yunus',
        totalAyahs: 109,
        juz: 11,
        revelationType: 'مكية'),
    SurahInfo(
        number: 11,
        nameArabic: 'هود',
        nameEnglish: 'Hud',
        totalAyahs: 123,
        juz: 11,
        revelationType: 'مكية'),
    SurahInfo(
        number: 12,
        nameArabic: 'يوسف',
        nameEnglish: 'Yusuf',
        totalAyahs: 111,
        juz: 12,
        revelationType: 'مكية'),
    SurahInfo(
        number: 13,
        nameArabic: 'الرعد',
        nameEnglish: 'Ar-Ra\'d',
        totalAyahs: 43,
        juz: 13,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 14,
        nameArabic: 'إبراهيم',
        nameEnglish: 'Ibrahim',
        totalAyahs: 52,
        juz: 13,
        revelationType: 'مكية'),
    SurahInfo(
        number: 15,
        nameArabic: 'الحجر',
        nameEnglish: 'Al-Hijr',
        totalAyahs: 99,
        juz: 14,
        revelationType: 'مكية'),
    SurahInfo(
        number: 16,
        nameArabic: 'النحل',
        nameEnglish: 'An-Nahl',
        totalAyahs: 128,
        juz: 14,
        revelationType: 'مكية'),
    SurahInfo(
        number: 17,
        nameArabic: 'الإسراء',
        nameEnglish: 'Al-Isra',
        totalAyahs: 111,
        juz: 15,
        revelationType: 'مكية'),
    SurahInfo(
        number: 18,
        nameArabic: 'الكهف',
        nameEnglish: 'Al-Kahf',
        totalAyahs: 110,
        juz: 15,
        revelationType: 'مكية'),
    SurahInfo(
        number: 19,
        nameArabic: 'مريم',
        nameEnglish: 'Maryam',
        totalAyahs: 98,
        juz: 16,
        revelationType: 'مكية'),
    SurahInfo(
        number: 20,
        nameArabic: 'طه',
        nameEnglish: 'Taha',
        totalAyahs: 135,
        juz: 16,
        revelationType: 'مكية'),
    SurahInfo(
        number: 21,
        nameArabic: 'الأنبياء',
        nameEnglish: 'Al-Anbya',
        totalAyahs: 112,
        juz: 17,
        revelationType: 'مكية'),
    SurahInfo(
        number: 22,
        nameArabic: 'الحج',
        nameEnglish: 'Al-Hajj',
        totalAyahs: 78,
        juz: 17,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 23,
        nameArabic: 'المؤمنون',
        nameEnglish: 'Al-Mu\'minun',
        totalAyahs: 118,
        juz: 18,
        revelationType: 'مكية'),
    SurahInfo(
        number: 24,
        nameArabic: 'النور',
        nameEnglish: 'An-Nur',
        totalAyahs: 64,
        juz: 18,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 25,
        nameArabic: 'الفرقان',
        nameEnglish: 'Al-Furqan',
        totalAyahs: 77,
        juz: 18,
        revelationType: 'مكية'),
    SurahInfo(
        number: 26,
        nameArabic: 'الشعراء',
        nameEnglish: 'Ash-Shu\'ara',
        totalAyahs: 227,
        juz: 19,
        revelationType: 'مكية'),
    SurahInfo(
        number: 27,
        nameArabic: 'النمل',
        nameEnglish: 'An-Naml',
        totalAyahs: 93,
        juz: 19,
        revelationType: 'مكية'),
    SurahInfo(
        number: 28,
        nameArabic: 'القصص',
        nameEnglish: 'Al-Qasas',
        totalAyahs: 88,
        juz: 20,
        revelationType: 'مكية'),
    SurahInfo(
        number: 29,
        nameArabic: 'العنكبوت',
        nameEnglish: 'Al-\'Ankabut',
        totalAyahs: 69,
        juz: 20,
        revelationType: 'مكية'),
    SurahInfo(
        number: 30,
        nameArabic: 'الروم',
        nameEnglish: 'Ar-Rum',
        totalAyahs: 60,
        juz: 21,
        revelationType: 'مكية'),
    SurahInfo(
        number: 31,
        nameArabic: 'لقمان',
        nameEnglish: 'Luqman',
        totalAyahs: 34,
        juz: 21,
        revelationType: 'مكية'),
    SurahInfo(
        number: 32,
        nameArabic: 'السجدة',
        nameEnglish: 'As-Sajdah',
        totalAyahs: 30,
        juz: 21,
        revelationType: 'مكية'),
    SurahInfo(
        number: 33,
        nameArabic: 'الأحزاب',
        nameEnglish: 'Al-Ahzab',
        totalAyahs: 73,
        juz: 21,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 34,
        nameArabic: 'سبأ',
        nameEnglish: 'Saba',
        totalAyahs: 54,
        juz: 22,
        revelationType: 'مكية'),
    SurahInfo(
        number: 35,
        nameArabic: 'فاطر',
        nameEnglish: 'Fatir',
        totalAyahs: 45,
        juz: 22,
        revelationType: 'مكية'),
    SurahInfo(
        number: 36,
        nameArabic: 'يس',
        nameEnglish: 'Ya-Sin',
        totalAyahs: 83,
        juz: 22,
        revelationType: 'مكية'),
    SurahInfo(
        number: 37,
        nameArabic: 'الصافات',
        nameEnglish: 'As-Saffat',
        totalAyahs: 182,
        juz: 23,
        revelationType: 'مكية'),
    SurahInfo(
        number: 38,
        nameArabic: 'ص',
        nameEnglish: 'Sad',
        totalAyahs: 88,
        juz: 23,
        revelationType: 'مكية'),
    SurahInfo(
        number: 39,
        nameArabic: 'الزمر',
        nameEnglish: 'Az-Zumar',
        totalAyahs: 75,
        juz: 23,
        revelationType: 'مكية'),
    SurahInfo(
        number: 40,
        nameArabic: 'غافر',
        nameEnglish: 'Ghafir',
        totalAyahs: 85,
        juz: 24,
        revelationType: 'مكية'),
    SurahInfo(
        number: 41,
        nameArabic: 'فصلت',
        nameEnglish: 'Fussilat',
        totalAyahs: 54,
        juz: 24,
        revelationType: 'مكية'),
    SurahInfo(
        number: 42,
        nameArabic: 'الشورى',
        nameEnglish: 'Ash-Shuraa',
        totalAyahs: 53,
        juz: 25,
        revelationType: 'مكية'),
    SurahInfo(
        number: 43,
        nameArabic: 'الزخرف',
        nameEnglish: 'Az-Zukhruf',
        totalAyahs: 89,
        juz: 25,
        revelationType: 'مكية'),
    SurahInfo(
        number: 44,
        nameArabic: 'الدخان',
        nameEnglish: 'Ad-Dukhan',
        totalAyahs: 59,
        juz: 25,
        revelationType: 'مكية'),
    SurahInfo(
        number: 45,
        nameArabic: 'الجاثية',
        nameEnglish: 'Al-Jathiyah',
        totalAyahs: 37,
        juz: 25,
        revelationType: 'مكية'),
    SurahInfo(
        number: 46,
        nameArabic: 'الأحقاف',
        nameEnglish: 'Al-Ahqaf',
        totalAyahs: 35,
        juz: 26,
        revelationType: 'مكية'),
    SurahInfo(
        number: 47,
        nameArabic: 'محمد',
        nameEnglish: 'Muhammad',
        totalAyahs: 38,
        juz: 26,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 48,
        nameArabic: 'الفتح',
        nameEnglish: 'Al-Fath',
        totalAyahs: 29,
        juz: 26,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 49,
        nameArabic: 'الحجرات',
        nameEnglish: 'Al-Hujurat',
        totalAyahs: 18,
        juz: 26,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 50,
        nameArabic: 'ق',
        nameEnglish: 'Qaf',
        totalAyahs: 45,
        juz: 26,
        revelationType: 'مكية'),
    SurahInfo(
        number: 51,
        nameArabic: 'الذاريات',
        nameEnglish: 'Adh-Dhariyat',
        totalAyahs: 60,
        juz: 26,
        revelationType: 'مكية'),
    SurahInfo(
        number: 52,
        nameArabic: 'الطور',
        nameEnglish: 'At-Tur',
        totalAyahs: 49,
        juz: 27,
        revelationType: 'مكية'),
    SurahInfo(
        number: 53,
        nameArabic: 'النجم',
        nameEnglish: 'An-Najm',
        totalAyahs: 62,
        juz: 27,
        revelationType: 'مكية'),
    SurahInfo(
        number: 54,
        nameArabic: 'القمر',
        nameEnglish: 'Al-Qamar',
        totalAyahs: 55,
        juz: 27,
        revelationType: 'مكية'),
    SurahInfo(
        number: 55,
        nameArabic: 'الرحمن',
        nameEnglish: 'Ar-Rahman',
        totalAyahs: 78,
        juz: 27,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 56,
        nameArabic: 'الواقعة',
        nameEnglish: 'Al-Waqi\'ah',
        totalAyahs: 96,
        juz: 27,
        revelationType: 'مكية'),
    SurahInfo(
        number: 57,
        nameArabic: 'الحديد',
        nameEnglish: 'Al-Hadid',
        totalAyahs: 29,
        juz: 27,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 58,
        nameArabic: 'المجادلة',
        nameEnglish: 'Al-Mujadila',
        totalAyahs: 22,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 59,
        nameArabic: 'الحشر',
        nameEnglish: 'Al-Hashr',
        totalAyahs: 24,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 60,
        nameArabic: 'الممتحنة',
        nameEnglish: 'Al-Mumtahanah',
        totalAyahs: 13,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 61,
        nameArabic: 'الصف',
        nameEnglish: 'As-Saf',
        totalAyahs: 14,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 62,
        nameArabic: 'الجمعة',
        nameEnglish: 'Al-Jumu\'ah',
        totalAyahs: 11,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 63,
        nameArabic: 'المنافقون',
        nameEnglish: 'Al-Munafiqun',
        totalAyahs: 11,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 64,
        nameArabic: 'التغابن',
        nameEnglish: 'At-Taghabun',
        totalAyahs: 18,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 65,
        nameArabic: 'الطلاق',
        nameEnglish: 'At-Talaq',
        totalAyahs: 12,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 66,
        nameArabic: 'التحريم',
        nameEnglish: 'At-Tahrim',
        totalAyahs: 12,
        juz: 28,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 67,
        nameArabic: 'الملك',
        nameEnglish: 'Al-Mulk',
        totalAyahs: 30,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 68,
        nameArabic: 'القلم',
        nameEnglish: 'Al-Qalam',
        totalAyahs: 52,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 69,
        nameArabic: 'الحاقة',
        nameEnglish: 'Al-Haqqah',
        totalAyahs: 52,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 70,
        nameArabic: 'المعارج',
        nameEnglish: 'Al-Ma\'arij',
        totalAyahs: 44,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 71,
        nameArabic: 'نوح',
        nameEnglish: 'Nuh',
        totalAyahs: 28,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 72,
        nameArabic: 'الجن',
        nameEnglish: 'Al-Jinn',
        totalAyahs: 28,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 73,
        nameArabic: 'المزمل',
        nameEnglish: 'Al-Muzzammil',
        totalAyahs: 20,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 74,
        nameArabic: 'المدثر',
        nameEnglish: 'Al-Muddaththir',
        totalAyahs: 56,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 75,
        nameArabic: 'القيامة',
        nameEnglish: 'Al-Qiyamah',
        totalAyahs: 40,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 76,
        nameArabic: 'الإنسان',
        nameEnglish: 'Al-Insan',
        totalAyahs: 31,
        juz: 29,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 77,
        nameArabic: 'المرسلات',
        nameEnglish: 'Al-Mursalat',
        totalAyahs: 50,
        juz: 29,
        revelationType: 'مكية'),
    SurahInfo(
        number: 78,
        nameArabic: 'النبأ',
        nameEnglish: 'An-Naba',
        totalAyahs: 40,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 79,
        nameArabic: 'النازعات',
        nameEnglish: 'An-Nazi\'at',
        totalAyahs: 46,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 80,
        nameArabic: 'عبس',
        nameEnglish: '\'Abasa',
        totalAyahs: 42,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 81,
        nameArabic: 'التكوير',
        nameEnglish: 'At-Takwir',
        totalAyahs: 29,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 82,
        nameArabic: 'الانفطار',
        nameEnglish: 'Al-Infitar',
        totalAyahs: 19,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 83,
        nameArabic: 'المطففين',
        nameEnglish: 'Al-Mutaffifin',
        totalAyahs: 36,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 84,
        nameArabic: 'الانشقاق',
        nameEnglish: 'Al-Inshiqaq',
        totalAyahs: 25,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 85,
        nameArabic: 'البروج',
        nameEnglish: 'Al-Buruj',
        totalAyahs: 22,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 86,
        nameArabic: 'الطارق',
        nameEnglish: 'At-Tariq',
        totalAyahs: 17,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 87,
        nameArabic: 'الأعلى',
        nameEnglish: 'Al-A\'la',
        totalAyahs: 19,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 88,
        nameArabic: 'الغاشية',
        nameEnglish: 'Al-Ghashiyah',
        totalAyahs: 26,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 89,
        nameArabic: 'الفجر',
        nameEnglish: 'Al-Fajr',
        totalAyahs: 30,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 90,
        nameArabic: 'البلد',
        nameEnglish: 'Al-Balad',
        totalAyahs: 20,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 91,
        nameArabic: 'الشمس',
        nameEnglish: 'Ash-Shams',
        totalAyahs: 15,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 92,
        nameArabic: 'الليل',
        nameEnglish: 'Al-Layl',
        totalAyahs: 21,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 93,
        nameArabic: 'الضحى',
        nameEnglish: 'Ad-Duhaa',
        totalAyahs: 11,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 94,
        nameArabic: 'الشرح',
        nameEnglish: 'Ash-Sharh',
        totalAyahs: 8,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 95,
        nameArabic: 'التين',
        nameEnglish: 'At-Tin',
        totalAyahs: 8,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 96,
        nameArabic: 'العلق',
        nameEnglish: 'Al-\'Alaq',
        totalAyahs: 19,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 97,
        nameArabic: 'القدر',
        nameEnglish: 'Al-Qadr',
        totalAyahs: 5,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 98,
        nameArabic: 'البينة',
        nameEnglish: 'Al-Bayyinah',
        totalAyahs: 8,
        juz: 30,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 99,
        nameArabic: 'الزلزلة',
        nameEnglish: 'Az-Zalzalah',
        totalAyahs: 8,
        juz: 30,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 100,
        nameArabic: 'العاديات',
        nameEnglish: 'Al-\'Adiyat',
        totalAyahs: 11,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 101,
        nameArabic: 'القارعة',
        nameEnglish: 'Al-Qari\'ah',
        totalAyahs: 11,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 102,
        nameArabic: 'التكاثر',
        nameEnglish: 'At-Takathur',
        totalAyahs: 8,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 103,
        nameArabic: 'العصر',
        nameEnglish: 'Al-\'Asr',
        totalAyahs: 3,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 104,
        nameArabic: 'الهمزة',
        nameEnglish: 'Al-Humazah',
        totalAyahs: 9,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 105,
        nameArabic: 'الفيل',
        nameEnglish: 'Al-Fil',
        totalAyahs: 5,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 106,
        nameArabic: 'قريش',
        nameEnglish: 'Quraysh',
        totalAyahs: 4,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 107,
        nameArabic: 'الماعون',
        nameEnglish: 'Al-Ma\'un',
        totalAyahs: 7,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 108,
        nameArabic: 'الكوثر',
        nameEnglish: 'Al-Kawthar',
        totalAyahs: 3,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 109,
        nameArabic: 'الكافرون',
        nameEnglish: 'Al-Kafirun',
        totalAyahs: 6,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 110,
        nameArabic: 'النصر',
        nameEnglish: 'An-Nasr',
        totalAyahs: 3,
        juz: 30,
        revelationType: 'مدنية'),
    SurahInfo(
        number: 111,
        nameArabic: 'المسد',
        nameEnglish: 'Al-Masad',
        totalAyahs: 5,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 112,
        nameArabic: 'الإخلاص',
        nameEnglish: 'Al-Ikhlas',
        totalAyahs: 4,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 113,
        nameArabic: 'الفلق',
        nameEnglish: 'Al-Falaq',
        totalAyahs: 5,
        juz: 30,
        revelationType: 'مكية'),
    SurahInfo(
        number: 114,
        nameArabic: 'الناس',
        nameEnglish: 'An-Nas',
        totalAyahs: 6,
        juz: 30,
        revelationType: 'مكية'),
  ];

  static SurahInfo? getSurahByNumber(int number) {
    try {
      return allSurahs.firstWhere((s) => s.number == number);
    } catch (e) {
      return null;
    }
  }

  static List<SurahInfo> getSurahsByJuz(int juz) {
    return allSurahs.where((s) => s.juz == juz).toList();
  }

  static int getTotalAyahs() {
    return allSurahs.fold(0, (sum, surah) => sum + surah.totalAyahs);
  }
}
